#
# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
schemaName: emall

dataSources:
  emall0:
    url: jdbc:mysql://127.0.0.1:3315/emall0?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: root
    connectionTimeoutMilliseconds: 30000
    idleTimeoutMilliseconds: 60000
    maxLifetimeMilliseconds: 1800000
    maxPoolSize: 20
  emall1:
    url: jdbc:mysql://127.0.0.1:3315/emall1?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: root
    connectionTimeoutMilliseconds: 30000
    idleTimeoutMilliseconds: 60000
    maxLifetimeMilliseconds: 1800000
    maxPoolSize: 20

    
rules:
- !SHARDING
  tables:
    orders: 
      actualDataNodes: emall${0..1}.orders${0..15}
      tableStrategy: 
        standard:
          shardingColumn: id
          shardingAlgorithmName: orders_inline
      keyGenerateStrategy: 
          column: id
          keyGeneratorName: snow
  defaultDatabaseStrategy:
    standard:
      shardingColumn: id
      shardingAlgorithmName: database_inline
  defaultTableStrategy:
    none:

  shardingAlgorithms:
    database_inline:
      type: INLINE
      props:
        algorithm-expression: emall${id % 2}
        allow-range-query-with-inline-sharding: true
    orders_inline:
      type: INLINE
      props:
        algorithm-expression: orders${id % 16}
        allow-range-query-with-inline-sharding: true
        
  keyGenerators:
    snow:
      type: SNOWFLAKE
      props:
        worker-id: 123
            



